export default function TermsPage() {
  return (
    <main style={{fontFamily:'system-ui,sans-serif',maxWidth:820,margin:'0 auto',padding:'40px 20px',lineHeight:1.7}}>
      <h1>Terms of Service</h1>
      <p><strong>Service:</strong> Shakin WhatsApp AI Bridge</p>
      <p><strong>Effective date:</strong> September 20, 2026</p>

      <h2>Use of the service</h2>
      <p>
        The service provides automated WhatsApp message routing and AI-assisted
        replies. You may use it only for lawful purposes and only where you have
        the right to send and receive the relevant messages.
      </p>

      <h2>Automated responses</h2>
      <p>
        Responses are generated by automation and AI systems and may contain
        errors. You are responsible for reviewing important information and for
        how you use any response generated by the service.
      </p>

      <h2>Acceptable use</h2>
      <p>
        You must not use the service for unlawful activity, abuse, harassment,
        unauthorized data collection, spam, or attempts to bypass security or
        platform restrictions.
      </p>

      <h2>Third-party platforms</h2>
      <p>
        The service depends on third-party platforms and integrations. Their
        availability and rules may change independently of this service.
      </p>

      <h2>Availability</h2>
      <p>
        The service is provided on an as-available basis. Interruptions may occur
        because of maintenance, outages, provider limits, network failures, or
        other technical issues.
      </p>

      <h2>Changes</h2>
      <p>
        These terms may be updated when the service changes. Continued use after
        an update constitutes use under the updated terms to the extent permitted
        by applicable law.
      </p>

      <p style={{marginTop:40}}>
        <a href="/privacy-policy">Privacy Policy</a>
        {' · '}
        <a href="/data-deletion">Data Deletion</a>
      </p>
    </main>
  );
}
